name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run security header scan
        run: |
          echo "Starting the security header verification..."
          chmod +x ./header-security-check.sh
          ./header-security-check.sh https://www.docker.com/ > security_report.txt

      - name: Upload security report artifact
        uses: actions/upload-artifact@v4
        with:
          name: security-report
          path: security_report.txt

  generate_pdf_docs:
    needs: build_and_test
    runs-on: ubuntu-latest
    container:
      image: pandoc/latex:latest
    steps:
      - name: Download security report artifact
        uses: actions/download-artifact@v4
        with:
          name: security-report
          path: ./

      - name: Generate PDF from security report
        run: |
          pandoc -s "security_report.txt" -o security-report.pdf \
          --pdf-engine=xelatex \
            -V geometry:margin=0.5in \
            -V fontsize=10pt \
            -V mainfont="DejaVu Sans"

      - name: Upload PDF report artifact
        uses: actions/upload-artifact@v4
        with:
          name: security-report-pdf
          path: security-report.pdf